# See https://rust-lang.github.io/rustfmt/
edition = "2024"
# version = "Two" # Use when ready
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
normalize_doc_attributes = true
wrap_comments = true
format_code_in_doc_comments = true
