[build]

[env]
# Stack backtraces.
RUST_BACKTRACE = "1"
# Set output levels for `tracing` logging.
RUST_LOG = "info"

[target.aarch64-apple-darwin]
linker = "rust-lld"

[target.x86_64-apple-darwin]
linker = "rust-lld"

[target.x86_64-unknown-linux-musl]
linker = "rust-lld"

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
